theme: jekyll-theme-minimal
title: Artjom Kurapov blog
description: Bookmark this to keep an eye on my project updates!
theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true